### ISSUE TITLE
Spelling Errors in the Book

### ISSUE THREAD

**Issue by PascalCorpsman** [penavon/BookPart1#1]
Dear Herbert,
i did not find any mail address to send the found Bugs to so i write them as issue to the Bookpart1 hoping that they find the way to your script.
I am reading part 1 in version 1.02 and until now found this issues

Page 23. 
you write digit = temp div 10
think it should be digit = temp mod 10

Page 24.
- in the comment you write F0 = 0 and F1 = 0 but your code sample sets F0 = 0 and F1 = 1 so either the comment or the code is wrong.
- in the bubblesort example there are 10 elements not 9 so it should be "lengthOfList = 10;"

thats for chapter 2 ;)

regards
Uwe Schächterle Alias PascalCorpsman

**Comment by Irwin1985** [comment]
Hi @PascalCorpsman 

You this is Herbert's email: hsauro@gmail.com

regards.

**Comment by PascalCorpsman** [comment]
thanks, ..
